run:
  timeout: 5m
  tests: true

linters:
  enable:
    - goimports
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - typecheck
    - gosec
    - misspell
    - lll
    - nakedret
    - prealloc
    - gocritic
    - gochecknoinits
    - gocyclo
    - gofmt
    - goprintffuncname
    - whitespace
    - unconvert
    - bodyclose
    - rowserrcheck
    - makezero
    - revive
    - exhaustive
    - copyloopvar

linters-settings:
  lll:
    line-length: 120
  gocyclo:
    min-complexity: 15
  govet:
    enable:
      - shadow

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - goconst