version: 2
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/blocc/main.go
    binary: blocc
    ldflags:
      - -s -w -X github.com/shuntaka9576/blocc/cli.Version={{ .Version }} -X github.com/shuntaka9576/blocc/cli.Revision={{ .ShortCommit }}
    goos:
      - linux
      - darwin
    ignore:
      - goarch: 386
      - goarch: arm64
archives:
  - name_template: >-
      {{- .ProjectName }}_{{ .Version }}_
      {{- if eq .Os "darwin" }}Darwin
      {{- else if eq .Os "linux" }}Linux
      {{- else }}{{ .Os }}{{ end }}_
      {{- .Arch }}
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  - repository:
      owner: shuntaka9576
      name: homebrew-tap
      token: "{{ .Env.GH_PAT }}"
    url_template: "https://github.com/shuntaka9576/blocc/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    homepage: "https://github.com/shuntaka9576/blocc"
    directory: Formula
    description: "Execute multiple commands and block Claude Code Hooks by returning exit 2 with stderr on failures 🛡️"
    test: |
      system "#{bin}/blocc --help"
    install: |
      bin.install "blocc"
